"""Migracao 09

Revision ID: ab2883ade47e
Revises: 5fb51c35c0a8
Create Date: 2025-07-27 00:05:17.431215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2883ade47e'
down_revision: Union[str, Sequence[str], None] = '5fb51c35c0a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('palavras', 'data',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('palavras', 'data',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
